import * as T from 'three';
import{OrbitControls}from'three/addons/controls/OrbitControls.js';
const P={
contrapposto:{l:'Contrapposto',n:'Weight settles through the left leg. Pelvis and shoulders counter-tilt.',r:[.02,-.06,-.07],pr:[-.02,.04,.08],j:{P:[0,1.10,0],C:[-.02,1.55,.01],N:[-.03,1.83,0],H:[-.04,2.04,.01],SL:[-.34,1.73,0],SR:[.31,1.78,.01],EL:[-.42,1.39,.05],ER:[.39,1.45,-.02],WL:[-.39,1.08,.10],WR:[.43,1.16,.05],HL:[-.20,1.08,0],HR:[.19,1.13,.01],KL:[-.18,.62,0],KR:[.24,.66,.11],AL:[-.17,.13,0],AR:[.29,.16,.19],TL:[-.17,.06,.18],TR:[.31,.08,.36]}},
reach:{l:'Reach',n:'Follow the action from the planted foot through pelvis, rib cage, and reaching hand.',r:[.04,-.16,.10],pr:[-.02,.10,-.02],j:{P:[.02,1.08,0],C:[-.08,1.53,.03],N:[-.14,1.81,.02],H:[-.17,2.02,.02],SL:[-.39,1.72,0],SR:[.22,1.67,.05],EL:[-.53,1.95,-.02],ER:[.38,1.39,.12],WL:[-.60,2.23,-.06],WR:[.44,1.09,.17],HL:[-.18,1.08,.02],HR:[.22,1.09,0],KL:[-.30,.65,.10],KR:[.27,.62,-.01],AL:[-.35,.18,.24],AR:[.29,.12,0],TL:[-.37,.08,.44],TR:[.29,.05,.20]}},
crouch:{l:'Crouch',n:'Study compression: rib cage approaches pelvis while thighs and shins fold under the body.',r:[-.28,0,0],pr:[.10,0,0],j:{P:[0,.93,.02],C:[-.05,1.33,.16],N:[-.08,1.58,.18],H:[-.10,1.78,.20],SL:[-.34,1.48,.13],SR:[.28,1.47,.14],EL:[-.43,1.18,.28],ER:[.39,1.17,.27],WL:[-.31,.95,.39],WR:[.29,.95,.39],HL:[-.20,.92,0],HR:[.20,.92,0],KL:[-.36,.56,.30],KR:[.36,.56,.30],AL:[-.20,.15,.12],AR:[.20,.15,.12],TL:[-.22,.07,.34],TR:[.22,.07,.34]}}
};
const M=[['reference','Reference','Surface study'],['construction','Construction','Instructor build-up'],['mass','Mass & Wedge','Bridgman-inspired'],['skeleton','Skeleton','Structural anatomy'],['landmarks','Landmarks','Surface anatomy']];
const Q={reference:['Compare head height to torso, pelvis, thigh, and lower leg.','Find bony landmarks before copying contour.','Orbit until the pose reads as forms, not silhouette.'],construction:['Place action, head, rib cage, and pelvis first.','Attach limb cylinders at actual joint centers.','Use cross-contours to check turning in space.'],mass:['Read rib cage and pelvis as opposing masses.','Look for compression and stretch.','Watch how limb masses taper through joints.'],skeleton:['Locate joint centers before soft tissue.','Track clavicles, sternum, spine, and pelvis tilt.','Ask which leg truly carries the weight.'],landmarks:['Find acromion, sternum, ASIS, patella, and ankle.','Use landmarks to anchor proportions.','Confirm the same relationships from every view.']};
let s={p:'contrapposto',m:'reference',g:true,b:3};
const el=id=>document.querySelector(id),stage=el('#three-stage'),scene=new T.Scene();scene.background=new T.Color(0xeee8dc);const cam=new T.PerspectiveCamera(31,1,.1,50);cam.position.set(3.05,1.55,3.55);const ren=new T.WebGLRenderer({antialias:true});ren.setPixelRatio(Math.min(devicePixelRatio||1,2));ren.shadowMap.enabled=true;ren.outputColorSpace=T.SRGBColorSpace;stage.appendChild(ren.domElement);const ctl=new OrbitControls(cam,ren.domElement);ctl.target.set(0,1.12,0);ctl.enableDamping=true;ctl.minDistance=2.5;ctl.maxDistance=8;ctl.update();scene.add(new T.HemisphereLight(0xfff8ee,0x6f675c,2.2));const dl=new T.DirectionalLight(0xfff4e7,3);dl.position.set(3,5,4);dl.castShadow=true;scene.add(dl);const floor=new T.Mesh(new T.CircleGeometry(3.3,48),new T.MeshStandardMaterial({color:0xd6ccbd,roughness:1}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);const grid=new T.GridHelper(5.6,24,0x958b7c,0xc8beb0);grid.position.y=.002;grid.material.opacity=.18;grid.material.transparent=true;scene.add(grid);
const root=new T.Group();scene.add(root);const G={ghost:new T.Group(),reference:new T.Group(),construction:new T.Group(),mass:new T.Group(),skeleton:new T.Group(),landmarks:new T.Group()};Object.values(G).forEach(x=>root.add(x));const C={surf:0x383832,light:0x55524b,bone:0xe7dfd1,warm:0xb7a78f,acc:0xdd603f,mass:0x716c62,land:0xe56343};const mat=(c,o=1,flat=false)=>new T.MeshStandardMaterial({color:c,roughness:.9,transparent:o<1,opacity:o,depthWrite:o>.2,flatShading:flat});const A={surf:mat(C.surf),light:mat(C.light),ghost:mat(C.surf,.13),warm:mat(C.warm,.22),bone:mat(C.bone),mass:mat(C.mass,1,true),mass2:mat(0x8b786a,1,true),land:mat(C.land),line:new T.LineBasicMaterial({color:0x5d5a52}),acc:new T.LineBasicMaterial({color:C.acc}),boneLine:new T.LineBasicMaterial({color:C.bone})};
const V=a=>new T.Vector3(...a),J=p=>Object.fromEntries(Object.entries(p.j).map(([k,a])=>[k,V(a)]));
function clear(g){while(g.children.length){const x=g.children.pop();x.traverse?.(n=>n.geometry?.dispose())}}
function ell(g,c,sc,m,seg=22,r=[0,0,0]){const x=new T.Mesh(new T.SphereGeometry(1,seg,Math.max(10,seg*.65|0)),m);x.position.copy(c);x.scale.set(...sc);x.rotation.set(...r);x.castShadow=true;g.add(x);return x}
function cyl(g,a,b,rt,rb,m,seg=16){const d=b.clone().sub(a),L=d.length(),x=new T.Mesh(new T.CylinderGeometry(rt,rb,L,seg),m);x.position.copy(a).add(b).multiplyScalar(.5);x.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());x.castShadow=true;g.add(x);return x}
function ln(g,a,b,m=A.line){const x=new T.Line(new T.BufferGeometry().setFromPoints([a,b]),m);g.add(x);return x}
function dot(g,p,r=.033,m=A.land){const x=new T.Mesh(new T.SphereGeometry(r,12,8),m);x.position.copy(p);g.add(x);return x}
function ring(g,c,rx,rz,r,m=A.line){const pts=[];for(let i=0;i<36;i++){const q=i/36*Math.PI*2;pts.push(new T.Vector3(Math.cos(q)*rx,0,Math.sin(q)*rz))}const x=new T.LineLoop(new T.BufferGeometry().setFromPoints(pts),m);x.position.copy(c);x.rotation.set(...r);g.add(x)}
function surface(g,p,m,detail=true){const j=J(p),r=p.r,pr=p.pr;ell(g,j.H,[.145,.185,.135],m,24,[0,r[1]*.4,r[2]*.2]);ell(g,j.N,[.08,.11,.075],m,18,r);ell(g,j.C,[.285,.34,.205],m,26,r);ell(g,j.C.clone().add(new T.Vector3(0,-.18,0)),[.22,.17,.17],m,22,r);ell(g,j.P,[.245,.18,.185],m,24,pr);[j.SL,j.SR].forEach(x=>ell(g,x,[.105,.11,.105],m,18));[['SL','EL',.074,.058],['SR','ER',.074,.058],['EL','WL',.058,.043],['ER','WR',.058,.043],['HL','KL',.115,.082],['HR','KR',.115,.082],['KL','AL',.088,.052],['KR','AR',.088,.052]].forEach(([a,b,x,y])=>cyl(g,j[a],j[b],x,y,m));['EL','ER','KL','KR'].forEach(k=>dot(g,j[k],.064,m));cyl(g,j.AL,j.TL,.065,.085,m,14);cyl(g,j.AR,j.TR,.065,.085,m,14);if(detail){ell(g,j.C.clone().add(new T.Vector3(-.11,.05,.15)),[.13,.08,.05],A.light,18,r);ell(g,j.C.clone().add(new T.Vector3(.11,.05,.15)),[.13,.08,.05],A.light,18,r)}}
function landmarks(p){const j=J(p);return[j.SL,j.SR,j.C.clone().add(new T.Vector3(0,.08,.19)),j.P.clone().add(new T.Vector3(-.18,.04,.13)),j.P.clone().add(new T.Vector3(.18,.04,.13)),j.KL.clone().add(new T.Vector3(0,0,.055)),j.KR.clone().add(new T.Vector3(0,0,.055)),j.AL,j.AR]}
function construct(g,p){const j=J(p),r=p.r,pr=p.pr,a=new T.Group(),b=new T.Group(),c=new T.Group(),d=new T.Group(),e=new T.Group();[a,b,c,d,e].forEach((x,i)=>{x.userData.stage=i+1;g.add(x)});ln(a,j.H.clone().add(new T.Vector3(0,.15,0)),j.N,A.acc);ln(a,j.N,j.C,A.acc);ln(a,j.C,j.P,A.acc);ln(a,j.P,j.AL.y<j.AR.y?j.AL:j.AR,A.acc);ell(b,j.H,[.145,.185,.135],A.warm,18);ell(b,j.C,[.285,.34,.205],A.warm,18,r);ell(b,j.P,[.245,.18,.185],A.warm,14,pr);ln(b,j.SL,j.SR);ln(b,j.HL,j.HR);[['SL','EL',.065,.052],['SR','ER',.065,.052],['EL','WL',.052,.040],['ER','WR',.052,.040],['HL','KL',.10,.074],['HR','KR',.10,.074],['KL','AL',.076,.045],['KR','AR',.076,.045]].forEach(([x,y,rt,rb])=>cyl(c,j[x],j[y],rt,rb,A.warm,12));['SL','SR','EL','ER','WL','WR','HL','HR','KL','KR','AL','AR'].forEach(k=>dot(c,j[k],.035,A.bone));ring(d,j.C,.285,.205,r);ring(d,j.P,.245,.185,pr);ring(d,j.H,.145,.135,[0,0,0]);landmarks(p).forEach(x=>dot(e,x,.025,A.land))}
function mass(g,p){const j=J(p);ell(g,j.H,[.15,.19,.14],A.mass,8,p.r);ell(g,j.C,[.30,.35,.22],A.mass2,8,p.r);ell(g,j.P,[.26,.19,.20],A.mass2,8,p.pr);[['SL','EL',.08,.056],['SR','ER',.08,.056],['EL','WL',.06,.043],['ER','WR',.06,.043],['HL','KL',.12,.08],['HR','KR',.12,.08],['KL','AL',.09,.05],['KR','AR',.09,.05]].forEach(([a,b,x,y])=>cyl(g,j[a],j[b],x,y,A.mass,6));ln(g,j.SL,j.SR,A.acc);ln(g,j.HL,j.HR,A.acc);ln(g,j.C,j.P,A.acc)}
function skeleton(g,p){const j=J(p);ell(g,j.H,[.125,.17,.115],A.bone,14);[['N','C'],['C','P'],['SL','SR'],['HL','HR']].forEach(([a,b])=>cyl(g,j[a],j[b],.019,.019,A.bone,8));[['SL','EL'],['SR','ER'],['EL','WL'],['ER','WR'],['HL','KL'],['HR','KR'],['KL','AL'],['KR','AR']].forEach(([a,b])=>cyl(g,j[a],j[b],.026,.021,A.bone,8));['SL','SR','EL','ER','WL','WR','HL','HR','KL','KR','AL','AR'].forEach(k=>dot(g,j[k],.041,A.bone));[-.16,-.08,0,.08,.16].forEach((dy,i)=>ring(g,j.C.clone().add(new T.Vector3(0,dy,0)),.20+(1-Math.abs(i-2)/3)*.075,.135+(1-Math.abs(i-2)/3)*.05,p.r,A.boneLine));ln(g,j.C.clone().add(new T.Vector3(0,.16,.18)),j.C.clone().add(new T.Vector3(0,-.13,.16)),A.acc)}
function rebuild(){Object.values(G).forEach(clear);const p=P[s.p];surface(G.ghost,p,A.ghost,false);surface(G.reference,p,A.surf,true);construct(G.construction,p);mass(G.mass,p);skeleton(G.skeleton,p);surface(G.landmarks,p,A.surf,true);landmarks(p).forEach(x=>dot(G.landmarks,x));show()}
function show(){Object.values(G).forEach(g=>g.visible=false);G[s.m].visible=true;if(s.g&&!['reference','landmarks'].includes(s.m))G.ghost.visible=true;G.construction.children.forEach(x=>x.visible=(x.userData.stage||1)<=s.b)}
function ui(){const p=P[s.p],m=M.find(x=>x[0]===s.m);el('#pose-list').innerHTML=Object.entries(P).map(([id,x])=>`<button class="pose-button ${id===s.p?'active':''}" data-pose="${id}"><span>${x.l}</span><small>${id===s.p?'Selected':'Study'}</small></button>`).join('');el('#instructor-note').textContent=p.n;el('#pose-title').textContent=p.l;el('#mode-kicker').textContent=m[2];el('#hud-mode').textContent=m[1];el('#hud-desc').textContent={reference:'Surface volumes on the same articulated rig.',construction:'Gesture, masses, joint centers, cylinders, planes, landmarks.',mass:'Planar masses emphasize weight, opposition, and compression.',skeleton:'Major bony axes and joint centers.',landmarks:'Surface figure with key drawing landmarks.'}[s.m];el('#mode-list').innerHTML=M.map((x,i)=>`<button class="mode-button ${x[0]===s.m?'active':''}" data-mode="${x[0]}"><span class="mode-index">0${i+1}</span><div><b>${x[1]}</b><small>${x[2]}</small></div></button>`).join('');el('#study-points').innerHTML=Q[s.m].map(x=>`<li>${x}</li>`).join('');el('#overlay-toggle').checked=s.g;el('#build-stage').value=s.b;el('#build-stage-label').textContent=`Stage ${s.b} of 5`;document.querySelectorAll('[data-pose]').forEach(b=>b.onclick=()=>{s.p=b.dataset.pose;ui();rebuild()});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{s.m=b.dataset.mode;ui();show()})}
const views={front:[0,1.48,4.5],three:[3.05,1.55,3.55],side:[4.55,1.48,0],back:[0,1.48,-4.5]};function view(k){cam.position.set(...views[k]);ctl.target.set(0,1.12,0);ctl.update()}document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));el('#reset-camera').onclick=()=>view('three');el('#overlay-toggle').onchange=e=>{s.g=e.target.checked;show()};el('#build-stage').oninput=e=>{s.b=+e.target.value;el('#build-stage-label').textContent=`Stage ${s.b} of 5`;show()};function resize(){const r=stage.getBoundingClientRect();ren.setSize(r.width,r.height,false);cam.aspect=r.width/r.height;cam.updateProjectionMatrix()}addEventListener('resize',resize);function loop(){ctl.update();ren.render(scene,cam);requestAnimationFrame(loop)}ui();rebuild();resize();loop();
